#!/bin/bash
usage(){
echo "You haven't provided a name"
echo "Usage: $0 name"
}
jaqen() {
local file="$1"
[[ -f $file ]] && return 0 || return 1
}
[[ $# -eq 0 ]] && usage
if ( jaqen "$1" )
then
echo "$1 exists"
else
echo "$1 doesn't exist"
fi
