#!/bin/bash
trap "echo Dont do that!" 2
echo "If you want something to go on, wait until 5 seconds are over"
hello_there() {
    secs=5
while (( $secs > 0 ))
do
echo $secs remaining
sleep 3
((--secs))
done
}
hello_there
